server:
  port: 8080

ninja:
  ninjaapikey: "TcUeQDdUJ2zbSjk2WGceVw==f1oa4hpKBoJSzvpf"
  ninjadictionaryurl: "https://api.api-ninjas.com/v1/dictionary"
  ninjarandomurl: "https://api.api-ninjas.com/v1/randomword"


redis:
  addr: "redis:6379"
  ttl: 300