version: '3.8'

services:
  app:
    image: calgor/englishpinglish:1730448751
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - app-network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - app
      - redis

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
