version: '3.8'

services:
  app:
    image: englishpinglish:v1.6
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
