apiVersion: apps/v1
kind: Deployment
metadata:
  name: englishpinglish-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: englishpinglish
  template:
    metadata:
      labels:
        app: englishpinglish
    spec:
      containers:
        - name: englishpinglish-container
          image: calgor/vocab:v1.4 
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          env:
            - name: NINJA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: englishpinglish-secret
                  key: ninjaAPIKey

      volumes:
        - name: config
          configMap:
            name: englishpinglish-configmap
