name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: |
        TIMESTAMP_TAG=${{ secrets.DOCKER_USERNAME }}/englishpinglish:$(date +%s)
        docker build . --file Dockerfile --tag $TIMESTAMP_TAG

    - name: Push the Docker image
      run: |
        docker push $TIMESTAMP_TAG
        docker push englishpinglish:latest
